version: "3"

services:
  nginx:
    image: "dgo/nginx"
    build:
      context: "${NGINX_DIR}/build"
    container_name: nginx  
    ports: 
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    expose:
      - "80"
      - "443"  
    volumes:
      - "${NGINX_DIR}/conf/nginx.conf:/etc/nginx/nginx.conf:rw"   
      - "${NGINX_DIR}/conf/conf.d:/etc/nginx/conf.d/:rw"
      - "${NGINX_DIR}/logs:/var/log/nginx/:rw"
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
  redis:
    image: "dgo/redis"
    build:
      context: "${REDIS_DIR}/build"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - "6379"
    volumes:
      - "${REDIS_DIR}/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw"
      - "${REDIS_DIR}/data:/data/:rw"
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
  mysql:
    image: "dgo/mysql"
    build:
      context: "${MYSQL_DIR}/build"  
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"
    volumes:
      - "${MYSQL_DIR}/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf:rw"  
      - "${MYSQL_DIR}/data:/var/lib/mysql/:rw"
      - "${MYSQL_DIR}/logs:/var/log/mysql/:rw"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    restart: always
    networks:
      - default 
  mongodb:
    image: "dgo/mongodb"
    build:
      context: "${MONGODB_DIR}/build"
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    expose:
      - "27017"
    volumes:
      - "${MONGODB_DIR}/conf/mongod.conf:/etc/mongo/mongod.conf:rw"  
      - "${MONGODB_DIR}/data:/data/db:rw"
      - "${MONGODB_DIR}/logs:/var/log/mongodb:rw"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
      TZ: "$TZ"
    restart: always
    networks:
      - default          
  pay:
    image: "dgo/pay"
    build:
      context: "${PAY_DIR}/build"
    container_name: pay
    ports:
      - "${PAY_PORT}:1729"
    expose:
      - "1729"
    volumes:
      - "${SOURCE_DIR}/pay:/www:rw"  
    environment:
      TZ: "$TZ"
    command:
      - go 
      - run
      - cmd/main.go
    restart: always
    networks:
      - default          



networks:
  default: