version: "3"

services:
  nginx:
    image: "romanticlie/nginx"
    depends_on:
      - cscke 
      - cscke-web
    container_name: nginx  
    ports: 
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    expose:
      - "80"
      - "443"  
    volumes:
      - "${NGINX_DIR}/conf/nginx.conf:/etc/nginx/nginx.conf:rw"   
      - "${NGINX_DIR}/conf/conf.d:/etc/nginx/conf.d/:rw"
      - "${NGINX_DIR}/logs:/var/log/nginx/:rw"
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
  redis:
    image: "romanticlie/redis"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - "6379"
    volumes:
      - "${REDIS_DIR}/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw"
      - "${REDIS_DIR}/data:/data/:rw"
    environment:
      TZ: "$TZ"
    restart: always
    networks:
      - default
  mysql:
    build:
      context: "${MYSQL_DIR}/build"
      dockerfile: Dockerfile-cscke
    container_name: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"
    volumes:
      - "${MYSQL_DIR}/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf:rw"  
      - "${MYSQL_DIR}/data:/var/lib/mysql/:rw"
      - "${MYSQL_DIR}/logs:/var/log/mysql/:rw"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"
    restart: always
    networks:
      - default 
  mongodb:
    image: "romanticlie/mongodb"
    container_name: mongodb
    ports:
      - "${MONGODB_PORT}:27017"
    expose:
      - "27017"
    volumes:
      - "${MONGODB_DIR}/conf/mongod.conf:/etc/mongo/mongod.conf:rw"  
      - "${MONGODB_DIR}/data:/data/db:rw"
      - "${MONGODB_DIR}/logs:/var/log/mongodb:rw"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
      TZ: "$TZ"
    restart: always
    networks:
      - default          
  cscke:
    image: "romanticlie/golang"
    depends_on:
      - redis
      - mysql 
      - mongodb
    container_name: cscke
    expose:
      - ${CSCKE_PORT}
    volumes:
      - "${GO_SOURCE_DIR}/cscke:/www:rw"  
    environment:
      TZ: "$TZ"
    command:
      - go 
      - run
      - cmd/api.go
    restart: always
    networks:
      - default
  cscke-web:
    image: "romanticlie/vue"
    container_name: cscke-web
    expose:
      - ${CSCKE_WEB_PORT}
    volumes:
      - "${WEB_SOURCE_DIR}/cscke-web:/www:rw"  
    environment:
      TZ: "$TZ"
    command:
      - yarn 
      - serve
    restart: always
    networks:
      - default
  

networks:
  default: